package org.ddahl

package object bamboo {

  val MajorVersion = "<<AUTOGENERATED>>"
  val FullVersion = "<<AUTOGENERATED>>"

  type Block = Tuple2[String,Int]
  type SSBlocks = List[Block]

  val AAOrder = Array("A","C","D","E","F","G","H","I","K","L","M","N","P","Q","R","S","T","V","W","Y")
  val AAIndexMap = AAOrder.zipWithIndex.toMap

  val SSOrder = Array("H","E","T","C")
  val SSIndexMap = SSOrder.zipWithIndex.toMap

}

